# Generated by Django 3.0.6 on 2020-06-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
    ]
