# Generated by Django 3.0.6 on 2020-06-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('books', '0002_remove_books_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genres.Genre', verbose_name='Жанр'),
        ),
    ]
