# Generated by Django 3.0.6 on 2020-07-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200716_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('view_all_books', 'Can view all books')]},
        ),
    ]
