# Generated by Django 3.0.6 on 2020-06-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userrequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adr', models.CharField(max_length=20, verbose_name='IP адрес')),
                ('date_request', models.DateField(default='0000-00-00', verbose_name='Дата')),
                ('safari', models.CharField(blank=True, max_length=10, null=True, verbose_name='Safari')),
                ('firefox', models.CharField(blank=True, max_length=10, null=True, verbose_name='Firefox')),
                ('unrefined_string', models.TextField(blank=True, null=True, verbose_name='Запрос')),
            ],
        ),
    ]
