# Generated by Django 3.0.6 on 2020-06-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequests',
            old_name='id',
            new_name='id_pr',
        ),
    ]
