# Generated by Django 3.0.6 on 2020-07-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0005_auto_20200712_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CANCELED', 'Отменён'), ('IN_PROCESSING', 'В обработке'), ('COMPLETED', 'Завершено')], default='IN_PROCESSING', max_length=20)),
                ('delivery_address', models.TextField(verbose_name='Delivery address')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Contact phone')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('basket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='basket.Basket')),
            ],
        ),
    ]
