# Generated by Django 3.0.6 on 2020-07-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200718_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Отменён', 'Отменён'), ('В обработке', 'В обработке'), ('Завершено', 'Завершено')], default='В обработке', max_length=20),
        ),
    ]
