# Generated by Django 3.0.6 on 2020-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200720_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_order',
            field=models.BooleanField(default=False, verbose_name='Отменить заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_order',
            field=models.BooleanField(default=False, verbose_name='Заказ доставлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Отменён', 'Отменён'), ('В обработке', 'В обработке'), ('Доставлен', 'Доставлен')], default='В обработке', max_length=20, verbose_name='Статус'),
        ),
    ]
