# Generated by Django 3.0.6 on 2020-07-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'permissions': [('view_all_genres', 'Can view all genres')]},
        ),
    ]
