# Generated by Django 3.0.6 on 2020-07-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания корзины')),
                ('basket_change_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения корзины')),
            ],
        ),
        migrations.CreateModel(
            name='BookInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('book_in_basket_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления книги в корзину')),
                ('book_in_basket_change_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения добавленной книги')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='basket.Basket')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_in_basket', to='books.Books')),
            ],
        ),
    ]
