# Generated by Django 3.0.6 on 2020-07-12 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0002_auto_20200707_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'session_key')},
        ),
    ]
