# Generated by Django 3.0.6 on 2020-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=191, unique=True, verbose_name='username')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Мобильный номер телефона')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('index', models.CharField(blank=True, max_length=30, null=True, verbose_name='Индекс')),
                ('adress1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Адрес прописки')),
                ('adress2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Адрес проживания')),
                ('additionally', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
