# Generated by Django 3.0.6 on 2020-07-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_all_profiles', 'Can view all profiles')]},
        ),
    ]
