# Generated by Django 3.0.6 on 2020-07-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200628_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additionally_2',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
