# Generated by Django 3.0.6 on 2020-07-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_additionally_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='additionally_2',
        ),
    ]
